name: Ruby CI

on:
  push:
    branches-ignore: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.2 ]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Update git submodules
        run: git submodule update --init --recursive
      - name: Install proper bundler gem
        run: gem install bundler -v 1.17.3
      - name: Install Ruby gems
        run: |
          gem install therubyracer
          bundle install
      - name: Run rake spec tasks
        env:
          EXECJS_RUNTIME: RubyRacer
        run: bundle exec rake spec